name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
          JDBC_DATABASE_USER: ${{ secrets.JDBC_DATABASE_USER }}
          JDBC_DATABASE_PASS: ${{ secrets.JDBC_DATABASE_PASS }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Snyk
        uses: snyk/actions@0.3.0
  release:
    needs: [build]
    runs-on: windows-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v1
         with:
           java-version: 17
       - name: Set Git user
         run: |
           git config user.email "ghactions@brianvermeer.nl"
           git config user.name "GitHub Actions"
       - name: Publish JAR
         run: mvn -B release:prepare release:perform -DskipTests
         env:
           JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
           JDBC_DATABASE_USER: ${{ secrets.JDBC_DATABASE_USER }}
           JDBC_DATABASE_PASS: ${{ secrets.JDBC_DATABASE_PASS }}
